title: mkwilson blog
description: mkwilson blog == mkwilson.tistory.com
theme: just-the-docs

url: https://mkwilson.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
